using System;

namespace Utils.Pagina.Attributes
{
    [AttributeUsage(AttributeTargets.Field, AllowMultiple = true, Inherited = false)]
    public class TFieldAttributeKey : System.Attribute
    {
        private bool m_Key;
        private bool m_Autogenerated;

        public TFieldAttributeKey(bool key, bool autogenerated)
        {
            this.m_Key = key;
            this.m_Autogenerated = autogenerated;
        }

        public bool key
        {
            get { return this.m_Key; }
        }

        public bool autogenerated
        {
            get { return this.m_Autogenerated; }
        }
    }
}
